name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Build container
      run: |
        cd test
        ./harness.sh docker
        exit $?
